# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  dotnet:
    build:
      context: "D:\\Fontys School\\Semester 3\\Projects\\SoundSteps_API\\SoundSteps.API"
      dockerfile: "Dockerfile"
    command: []
    entrypoint:
    - "dotnet"
    - "/app-1/bin/Debug/net8.0/SoundSteps.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "mcr.microsoft.com/dotnet/aspnet:dev"
    ports: []
    volumes:
    - "D:\\Fontys School\\Semester 3\\Projects\\SoundSteps_API\\SoundSteps.API:/app-1:rw"
    - "D:\\Fontys School\\Semester 3\\Projects\\SoundSteps_API:/src:rw"
    - "C:\\Users\\Thomas (School)\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app-1"
