name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx for building Docker images
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Set up .NET Core SDK for backend build
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    # Restore .NET dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build .NET backend application
    - name: Build
      run: dotnet build --no-restore --configuration Release

    # Run backend tests
    - name: Run tests
      run: dotnet test --no-build --verbosity normal --configuration Release

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push the backend Docker image
    - name: Build and push Docker image (backend)
      uses: docker/build-push-action@v4
      with:
        context: .  # Assuming Dockerfile is at the root or adjust accordingly
        file: SoundSteps.API/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/soundsteps:dev

    # Run the backend container for testing
    - name: Run backend container
      run: |
        docker run -d --name backend-container -p 8081:8081 ${{ secrets.DOCKER_USERNAME }}/soundsteps:dev
        sleep 10 # Wait for the container to start properly

    # OWASP ZAP Security Scan
    - name: OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.8.0
      with:
        target: "http://localhost:5029"  # Adjust based on where the API is exposed
        fail-action: true  # Set to true to fail the pipeline if vulnerabilities are found
        cmd-options: "-a"  # Enable active scan for better coverage

    # Stop the backend container
    - name: Stop backend container
      run: docker stop backend-container
