name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    
    - name: Restore dependencies
      run: dotnet restore

    
    - name: Build
      run: dotnet build --no-restore --configuration Release

    
    - name: Run tests
      run: dotnet test --no-build --verbosity normal --configuration Release

    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    
    - name: Build and push Docker image (backend)
      uses: docker/build-push-action@v4
      with:
        context: .  
        file: SoundSteps.API/Dockerfile  
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/soundsteps:dev  
